export const TOGGLE_DARKMODE = 'TOGGLE_DARKMODE';
export const TOGGLE_DARKMODE_SUCCESS = 'TOGGLE_DARKMODE_SUCCESS';
export const GET_PRODUCTS = 'PRODUCT/GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'PRODUCT/GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'PRODUCT/GET_PRODUCTS_FAIL';
