export const TOGGLE_DARKMODE = 'TOGGLE_DARKMODE';
export const TOGGLE_DARKMODE_SUCCESS = 'TOGGLE_DARKMODE_SUCCESS';
export const GET_PRODUCTS = 'PRODUCT/GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'PRODUCT/GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'PRODUCT/GET_PRODUCTS_FAIL';
export const UPDATE_PRODUCTS = 'PRODUCT/UPDATE_PRODUCTS';
export const UPDATE_PRODUCTS_SUCCESS = 'PRODUCT/UPDATE_PRODUCTS_SUCCESS';
export const UPDATE_PRODUCTS_FAIL = 'PRODUCT/UPDATE_PRODUCTS_FAIL';


export const ADD_PRODUCT_TO_CART = 'PRODUCT/ADD_PRODUCT_TO_CART';
export const SUB_PRODUCT_FROM_CART = 'PRODUCT/SUB_PRODUCT_FROM_CART';
export const REMOVE_PRODUCT_FROM_CART = 'PRODUCT/REMOVE_PRODUCT_FROM_CART';

export const GET_FULL_INFO_READ_ONLY_CART = 'PRODUCT/GET_FULL_INFO_READ_ONLY_CART';


export const COLORS = {
    NUTRILITE: '#f3f7eb',
    ARTISTRY: '#f1ece7',
    HOMECARE: '#edf5f9',
    PERSONALCARE: '#ebebf5',
    DEFAULT: '#ffffff'
}

export const CATEGORIES = ['TẤT CẢ', 'NUTRILITE', 'ARTISTRY', 'PERSONALCARE', 'HOMECARE']